# site settings
title: '2ùëì ¬ª Second Order Harmonics'
subtitle: "‚Ä¶Analogue Sound for the Digital Age‚Ä¶"
email: info@secondorderharmonics.eu
description: "High-quality Analog Audio Gear & custom builds"
baseurl: ""
url: https://secondorderharmonics.com
author: Aaron Zauner
street_address: "Second Order Harmonics<br />(&mdash;per&mdash; Aaron Zauner)<br />Zentaplatz 7/17"
city: Vienna
zip_code: 1050
country: Austria / EU
phone: "+43 664 639 4757"

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 7

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  Shop: https://reverb.com/shop/secondorderharmonics
  Ebay: https://www.ebay.com/usr/az_et
  github-alt: https://github.com/SecondOrderHarmonics
  Patreon: https://www.patreon.com/secondorderharmonics
  Facebook: https://www.facebook.com/profile.php?id=100090381861518
  Whatsapp: https://wa.link/tifdl9

# build settings
markdown: kramdown

sass:
  style: compressed

collections:
  products:
    output: true

# Outputting
#permalink: /:categories/:title/
timezone: Europe/Vienna

# Pliugins
plugins:
- jekyll-remote-theme

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md

#EOF
